<?php
/***********************************************************************************/
/* WARNING:                                                                        */
/* The wp-config.php file is automatically generated by Flywheel. You will not be  */
/* able to edit this file yourself. Defines needed for plugins can be added to a   */
/* php file in your wp-content/mu-plugins directory. If you need to add defines    */
/* for core WordPress functionality, please contact Flywheel support at            */
/* help@getflywheel.com.                                                           */
/***********************************************************************************/

define('FLYWHEEL_CONFIG_DIR', dirname(__FILE__) . '/flywheel-config');
define('FLYWHEEL_PLUGIN_DIR', FLYWHEEL_CONFIG_DIR . '/plugins');
define('FLYWHEEL_DEFAULT_PROTOCOL', 'http://');
define('WPMU_PLUGIN_DIR', dirname(__FILE__) . '/wp-content/mu-plugins');
define('WPMU_PLUGIN_URL', '/wp-content/mu-plugins');
define('FS_METHOD', 'direct');
define('WP_POST_REVISIONS',  10);
define('WP_MEMORY_LIMIT', '128M');




/****************************************************************************/
/*                         Database Configuration                           */
/****************************************************************************/
define('DB_NAME', 'db4278970743');
define('DB_USER', 'root');
define('DB_PASSWORD', '');
define('DB_HOST', '127.0.0.1');
define('DB_CHARSET', 'latin1');
define('DB_COLLATE', 'latin1_swedish_ci');
$table_prefix  = 'wp_';






/****************************************************************************/
/*                             WordPress Salts                              */
/****************************************************************************/
define('AUTH_KEY',          'Ufz,:zDxzGv|zf4s8:FbpID)E=gm%)Rb#h.yTW#}8MY&RNOt0.W#)NS!iCE$_f[N');
define('SECURE_AUTH_KEY',   'd+?k/`:2lz:Dazh.Z,<cEFPYmy^P4Yf[puyQDQNfg|C7Nd=[1)Sj:>kXT;(d0`aF');
define('LOGGED_IN_KEY',     'lwedMji_(2/ExGdT3VQ>vt9{xrgj44]=/hsH(4o9KDwqm?*@_h{Sm+pqW$_Oz>ge');
define('NONCE_KEY',         'J3cz_tK^IXcI821_Mkl#GrG1=+/_F)7s(ICBt$~B*OKErQgjzMn*d61!%;O%w_Kk');
define('AUTH_SALT',         'Xn#lV+~2*b)e^$H!>:fIMROotbNT6ewp/:DNQK:t-.n1@z#7^Jd34tvKv>[CuVq+');
define('SECURE_AUTH_SALT',  '{=A-z)hzK5$FVFbX~Qj7bEv3W>S,G2SutJ;P7{2kqs/Fxf[oqA4X!hCHTrq/Lqn;');
define('LOGGED_IN_SALT',    '|,%qX(#<IwPs!;m3v[0Z[(@KPrC0{*6>b>S:~!aB}zIztEVQ*Az97<=U#cm?uK(,');
define('NONCE_SALT',        '7l@}I7p3[3]N!okgYE8)#sMwB>1(Q,{Uay@9Sn?@~|oT=wBoA?`It^os)%bVU^[s');


/****************************************************************************/
/*                        General WordPress Settings                        */
/****************************************************************************/
define('WPLANG', '');
define('WP_DEBUG', false);
define('WP_CACHE', false);


/****************************************************************************/
/*                              Custom Content                              */
/****************************************************************************/



/****************************************************************************/
/*                     Disable WordPress Auto-updates                       */
/*           http://getflywheel.com/flywheel-wordpress-3-7/                 */
/****************************************************************************/
define('WP_AUTO_UPDATE_CORE', false);


if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

if ( array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' )
	$_SERVER['HTTPS']='on';



require_once(ABSPATH . 'wp-settings.php');
